services:
  webapp:
    build: ./webapp
    container_name: webapp
    restart: always
    ports:
      - "4200:80"
    volumes:
      - ./webapp:/app
      - /app/node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true
    - FAST_REFRESH=false
    depends_on:
      - api
    networks:
      - app_network

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/stock-trading-app
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_DATABASE: stock-trading-app
    command: ["mongod", "--bind_ip_all"]
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp
      - api
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
